server:
  port: 8092

spring:
  application:
    name: employee-service

springdoc:
  version: '@springdoc.version@'

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

app:
  feign:
    department-service:
      name: department-service
      url: http://localhost:8090
    organization-service:
      name: organization-service
      url: http://localhost:8091