apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: employee-service-deploy
  name: employee-service
  namespace: oe
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: employee-service-deploy
  type: NodePort
status:
  loadBalancer: {}
