apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - namespace.yml
  - employee-deployment.yml
  - organization-deployment.yml
  - employee-service.yml
  - organization-service.yml

configMapGenerator:
  - name: employee-service-cm
    files:
      - application.yml=employee-application.yml
  - name: organization-service-cm
    files:
      - application.yml=organization-application.yml
generatorOptions:
  disableNameSuffixHash: true