apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - namespace.yml
  - service.yml
  - deployment.yml

configMapGenerator:
  - name: employee-service-cm
    files:
      - application.yml
generatorOptions:
  disableNameSuffixHash: true