apiVersion: v1
kind: Service
metadata:
  labels:
    app: organization-service-deploy
  name: organization-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: organization-service-deploy
  type: ClusterIP
