apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: organization-service-deploy
  name: organization-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization-service-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: organization-service-deploy
    spec:
      containers:
        - image: localhost:5000/organization-service:1.0.0
          name: organization-service
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
          resources: {}
      volumes:
        - name: config-volume
          configMap:
            name: organization-service-cm
