apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: employee-service-deploy
  name: employee-service
  namespace: oe
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: employee-service-deploy
  type: ClusterIP
